// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Navigation/Footer.vue')['default']
    Header: typeof import('./src/components/Navigation/Header.vue')['default']
    ListPages: typeof import('./src/components/Articles/ListPages.vue')['default']
    ListTables: typeof import('./src/components/Articles/ListTables.vue')['default']
    Paginate: typeof import('./src/components/Pagination/Paginate.vue')['default']
    Post: typeof import('./src/components/Articles/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./src/components/Navigation/Side.vue')['default']
    Tag: typeof import('./src/components/customcomponent/Tag.vue')['default']
    TagCloud: typeof import('./src/components/customcomponent/TagCloud.vue')['default']
    Top: typeof import('./src/components/Navigation/Top.vue')['default']
  }
}

export {}
