// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('C:/Users/user/Documents/github/ftml-wdfiles/src/components/Articles/Article.vue')['default']
    ImageThree: typeof import('C:/Users/user/Documents/github/ftml-wdfiles/src/components/Image/ImageThree.vue')['default']
    ImageTwo: typeof import('C:/Users/user/Documents/github/ftml-wdfiles/src/components/Image/ImageTwo.vue')['default']
    Paginate: typeof import('C:/Users/user/Documents/github/ftml-wdfiles/src/components/Pagination/Paginate.vue')['default']
    Post: typeof import('C:/Users/user/Documents/github/ftml-wdfiles/src/components/Articles/Post.vue')['default']
  }
}

export { }
